DROP TABLE IF EXISTS HarjoitusRyhmaIlmoittautuminen;
DROP TABLE IF EXISTS Opetusaika CASCADE;
DROP TABLE IF EXISTS Kurssisuoritus CASCADE;
DROP TABLE IF EXISTS KurssiIlmoittautuminen CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Kurssi CASCADE;
DROP TABLE IF EXISTS Vastuuyksikko CASCADE;
